apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn
  namespace: q1
  labels:
    team: digisos
spec:
  image: navikt/sosialhjelp-innsyn:latest
  port: 8080
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isAlive
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 1
    max: 4
  ingresses:
    - "https://sosialhjelp-innsyn.dev-sbs.nais.io/"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
  env:
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: NAV_TRUSTSTORE_PATH
      value: /var/run/secrets/naisd.io/nav_truststore_path
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice-q.nav.no/login
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD
    - name: UNLEASH_API_URL
      value: https://unleashproxy.nais.oera.no/api/
    - name: LOADBALANCER_SOKNAD_KONTANTSTOTTE_URL
      value: soknad-kontantstotte-q.nav.no
    - name: LOADBALANCER_SOKNAD_KONTANTSTOTTE_POOLNAME
      value: na


