apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn/internal/isAlive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /actuator/metrics
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  ingresses:
{{#each ingresses}}
    - "{{this}}"
{{/each}}
  webproxy: true
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  vault:
    enabled: false
  env:
    - name: DEKORATOR_MILJO
      value: {{dekoratorMiljo}}
    - name: INNSYN_API_SINGLE_LOGOUT_URL
      value: {{innsyn-api-single-logout-url}}
