version: 2.1

jobs:
  bygg:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            # when lock file changes, use increasingly general patterns to restore cache
#            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
#            - node-v1-{{ .Branch }}-
#            - node-v1-
#      - run:
#          name: Bygg React app
#          command: |
#            npm ci
#            npm run build
#      - save_cache:
#          paths:
#            - ~/usr/local/lib/node_modules # location depends on npm version
#          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - setup_remote_docker
      - run:
          name: Bygger Docker image
          command:
            docker build -t "navikt/sosialhjelp-innsyn:latest" .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "navikt/sosialhjelp-innsyn:latest"

  deploy_dev:
    docker:
      - image: navikt/deployment-cli:v0.1.5
    steps:
      - checkout
      - setup_remote_docker
      - run: # Brukernavn og passord til Github ligger i miljøvariablene DEPLOYMENT_USERNAME og DEPLOYMENT_PASSWORD. TODO: legge til støtte for deploy til prod
          name: Deploy til default dev-sbs
          command: |
            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn-api --team=digisos -r=deploy/nais.yaml --version=${CIRCLE_SHA1} --vars=nais/dev/default.json



workflows:
  version: 2.1
  bygg-og-publish-image:
    jobs:
      - bygg
      - deploy_dev:
          filters:
            branches:
              only: master
