name: Deploy to environment
on:
  repository_dispatch:
    types: [q0, q1, p]

jobs:
  deploy-q0:
    name: Deploy to q0
    runs-on: ubuntu-latest
    if: github.event.action == 'q0'
    steps:
      - run: |
          git clone https://github.com/navikt/sosialhjelp-ci.git
          # FIXME: Remove version number substitution when GitHub Actions replaces CircleCI
          VERSION="$(sosialhjelp-ci/bin/create-artifact-version.sh | sed 's/^1.0/1.1/')"
          deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/${MILJO}.json

  deploy-q1:
    name: Deploy to q1
    runs-on: ubuntu-latest
    if: github.event.action == 'q1'
    steps:
      - run: |
          git clone https://github.com/navikt/sosialhjelp-ci.git
          # FIXME: Remove version number substitution when GitHub Actions replaces CircleCI
          VERSION="$(sosialhjelp-ci/bin/create-artifact-version.sh | sed 's/^1.0/1.1/')"
          deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-innsyn --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/${MILJO}.json

  deploy-p:
    name: Deploy to prod
    runs-on: ubuntu-latest
    if: github.event.action == 'p'
    steps:
      - run: |
          git clone https://github.com/navikt/sosialhjelp-ci.git
          # FIXME: Remove version number substitution when GitHub Actions replaces CircleCI
          VERSION="$(sosialhjelp-ci/bin/create-artifact-version.sh | sed 's/^1.0/1.1/')"
          deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-innsyn --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/prod/default.json
