name: Deploy til dev
on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'dev-sbs'
        type: choice
        options:
          - 'dev'
          - 'mock'
          - 'dev-sbs'
          - 'labs-gcp'

jobs:
  deploy:
    name: Deploy to dev - ${{ github.event.inputs.config-file-name }}
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
    steps:

      - name: Sett cluster basert på config-file
        run: |
          if [[ ${{ github.event.inputs.config-file-name }} = 'dev-sbs' ]]; then
            echo "CLUSTER_NAME=dev-sbs" >> $GITHUB_ENV
          elif [[ ${{ github.event.inputs.config-file-name }} = 'labs-gcp' ]]; then
            echo "CLUSTER_NAME=labs-gcp" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=dev-gcp" >> $GITHUB_ENV
          fi
      - name: echo cluster
        run: |
          echo "${{ env.CLUSTER_NAME }}"

