name: Deploy and test on Heroku
on:
  push:
    branches:
      - master

jobs:
  deploy-heroku:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy on Heroku
        run: |
          # HEROKU_USERNAME must be URL encoded, eg. joachim.liepelt%40nav.no
          PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
          env
          git remote add heroku https://$HEROKU_USERNAME:$HEROKU_AUTH_TOKEN@git.heroku.com/$PROJECT_NAME.git
          git push heroku $GITHUB_BRANCH:master --force
        env:
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}

  browser-test:
    name: Test on Heroku
    runs-on: ubuntu-latest
    needs: deploy-heroku
    steps:
      - name: Run browser tests
        run: |
          set -eo pipefail
          git clone https://github.com/navikt/sosialhjelp-tester.git
          cd sosialhjelp-tester

          npm install
          npm run saucelabs-innsyn
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_API_HOST: ${{ secrets.SAUCE_API_HOST }}
          SAUCE_USERNAME: ${{ secrets. SAUCE_USERNAME }}
