name: npm audit
on:
  push:
    branches:
      - "**" # Build all branches
    tags-ignore:
      - "**" # Don't build any tags

env:
  CI: true

jobs:
  build:
    name: Run npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit
        run: npm audit --production --audit-level=moderate # Denne kan justeres hvis vi ønsker at bygg brekker på sårbarheter lavere enn moderate. Mulige verdier er low|moderate|high|critical
